site_name: BrainSwipes
theme: readthedocs
plugins:
  - search
docs_dir: docs
nav:
  - Welcome: index.md
  - Architecture:
      - Overview: architecture.md
      - AWS: aws.md
      - Firebase: firebase.md
      - MSI: msi.md
  - Development:
      - Setup: setup.md
      - Deployment: deployment.md
  - Management:
      - Configuration: configuration.md
      - Data Ingestion: ingest.md
      - Tools: tools.md
